# Generated by Django 2.2.4 on 2019-09-09 13:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Linux', 'Linux'), ('Django', 'Django'), ('Java', 'Java'), ('ML', 'ML')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('blog_photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('member_about', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_details', models.CharField(max_length=40)),
                ('description', ckeditor.fields.RichTextField()),
                ('blog_details_photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('comments', models.TextField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.BlogCategory')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
