# Generated by Django 2.2.4 on 2019-11-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_blogdetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='created_by',
        ),
    ]
