# Generated by Django 2.2.4 on 2019-11-12 10:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_blogdetails_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='blog_details_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Attachments/', verbose_name='Code Snippet'),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='short_details',
            field=models.CharField(max_length=40, verbose_name='Short Details'),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.BlogCategory', verbose_name='Technology'),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Written By'),
        ),
    ]
