# Generated by Django 2.2.4 on 2019-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20191120_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
