# Generated by Django 2.2.4 on 2019-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_blogdetails_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='approved',
            field=models.BooleanField(default='False'),
        ),
    ]
