# Generated by Django 2.2.4 on 2019-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20191209_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
