# Generated by Django 2.2.4 on 2019-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20191220_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
