# Generated by Django 2.2.4 on 2020-01-08 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20191227_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
