# Generated by Django 2.2.4 on 2020-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_remove_blogcomments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
    ]
