# Generated by Django 2.2.4 on 2020-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20200108_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='liked_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
