# Generated by Django 2.2.4 on 2020-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_blogcomments_liked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='liked_user',
            field=models.TextField(blank=True, default='string', null=True),
        ),
    ]
