# Generated by Django 2.2.4 on 2020-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_auto_20200108_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='liked_user',
            field=models.TextField(default='string'),
        ),
    ]
